import {
  Category,
  GroupWithMembers,
  ItemWithDetails,
  Notification,
  Routine,
  Schedule,
  User,
} from "@/types";

// Dummy shared members
export const sharedMembers: User[] = [
  {
    id: "m1",
    nickname: "민지",
    provider: "kakao",
    providerId: "kakao-123",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "m2",
    nickname: "철수",
    provider: "google",
    providerId: "google-456",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "m3",
    nickname: "영희",
    provider: "apple",
    providerId: "apple-789",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "me", // 추가: 현재 사용자(나)의 정보
    nickname: "사용자",
    provider: "kakao",
    providerId: "kakao-me",
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

// Dummy groups
export const initialGroups: GroupWithMembers[] = [
  {
    id: "personal",
    name: "개인",
    description: null,
    memberCount: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "home",
    name: "우리 집",
    description: null,
    memberCount: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "club",
    name: "동아리",
    description: null,
    memberCount: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const initialItems: ItemWithDetails[] = [
  {
    id: "1",
    name: "세탁세제",
    category: "다이소",
    placeName: "강남역 다이소",
    address: null,
    lat: 37.5665,
    lng: 126.978,
    placeId: null,
    completed: false,
    memo: "무향 제품으로 구매하기",
    addedById: "m1",
    groupId: "home",
    purchasingById: null,
    scheduleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    addedBy: { id: sharedMembers[0].id, nickname: sharedMembers[0].nickname },
    purchasingBy: null,
  },
  {
    id: "2",
    name: "우유",
    category: "마트",
    placeName: "이마트 역삼점",
    address: null,
    lat: 37.5012,
    lng: 127.0396,
    placeId: null,
    completed: false,
    memo: "저지방 1L 2개",
    addedById: "m2",
    groupId: "home",
    purchasingById: "m2",
    scheduleId: "s5",
    createdAt: new Date(),
    updatedAt: new Date(),
    addedBy: { id: sharedMembers[1].id, nickname: sharedMembers[1].nickname },
    purchasingBy: { id: sharedMembers[1].id, nickname: sharedMembers[1].nickname },
  },
  {
    id: "3",
    name: "감기약",
    category: "약국",
    placeName: "온누리약국",
    address: null,
    lat: 37.4979,
    lng: 127.0276,
    placeId: null,
    completed: false,
    memo: null,
    addedById: "me",
    groupId: "personal",
    purchasingById: null,
    scheduleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    addedBy: { id: sharedMembers[3].id, nickname: sharedMembers[3].nickname },
    purchasingBy: null,
  },
];

export const initialSchedules: Schedule[] = [
  {
    id: "s1",
    title: "출근",
    startTime: new Date("2024-01-01T08:30:00"),
    endTime: new Date("2024-01-01T09:00:00"),
    location: "집 -> 회사",
    status: "past",
    calendarSource: "routine",
    calendarEventId: null,
    isRoutine: true,
    userId: "me",
    routineId: "r1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "s2",
    title: "주간 회의",
    startTime: new Date("2024-01-01T10:00:00"),
    endTime: new Date("2024-01-01T11:00:00"),
    location: "회사 회의실",
    status: "past",
    calendarSource: "google",
    calendarEventId: "google-event-123",
    isRoutine: false,
    userId: "me",
    routineId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "s5",
    title: "퇴근",
    startTime: new Date("2024-01-01T18:00:00"),
    endTime: new Date("2024-01-01T18:30:00"),
    location: "회사 -> 집",
    status: "upcoming",
    calendarSource: "routine",
    calendarEventId: null,
    isRoutine: true,
    userId: "me",
    routineId: "r1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const initialNotifications: Notification[] = [
  {
    id: "n1",
    type: "enter",
    message: "강남역 다이소 근처입니다. 세탁세제를 구매하세요!",
    isRead: false,
    userId: "me",
    groupId: "home",
    createdAt: new Date(),
  },
  {
    id: "n2",
    type: "enter",
    message: "이마트 역삼점이 100m 앞에 있습니다.",
    isRead: false,
    userId: "me",
    groupId: "home",
    createdAt: new Date(),
  },
  {
    id: "n3",
    type: "purchased",
    message: "철수님이 삼각김밥을 구매했습니다.",
    isRead: true,
    userId: "me",
    groupId: "personal",
    createdAt: new Date(),
  },
];

export const initialRoutines: Routine[] = [
  {
    id: "r1",
    name: "출퇴근",
    startLocation: "집",
    endLocation: "회사",
    startTime: "08:30",
    endTime: "18:00",
    isRoundTrip: true,
    daysOfWeek: 31, // 월화수목금
    userId: "me",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const categories: Category[] = [
  { id: "all", label: "전체" },
  { id: "daiso", label: "다이소" },
  { id: "mart", label: "마트" },
  { id: "convenience", label: "편의점" },
  { id: "pharmacy", label: "약국" },
  { id: "bakery", label: "베이커리" },
];
